name 'cerny_common'
maintainer 'Nathan Cerny'
maintainer_email 'ncerny@gmail.com'
license 'apache2'
description 'cerny environment common cookbook'
long_description 'The base/common cookbook for my personal environment.'
version '0.1.1'

depends 'ntp'
depends 'chef-client'
